// This file was autogenerated by Visual Studio MVC Template

using System;
using System.Diagnostics;
using System.Reflection;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;

namespace Bd.GithubAnalyzer
{
	public class Program
	{
		public static void Main(string[] args)
		{
			var assemblyName = Assembly.GetExecutingAssembly().GetName();
			var currentProcess = Process.GetCurrentProcess();
			Console.Title = $"PID({currentProcess.Id}) {assemblyName}";

			CreateHostBuilder(args).Build().Run();
		}

		public static IHostBuilder CreateHostBuilder(string[] args) =>
			Host.CreateDefaultBuilder(args)
				.ConfigureWebHostDefaults(webBuilder =>
				{
					webBuilder.UseStartup<Startup>();
				});
	}
}
